name: Update software versions

on:
  #schedule:
  #- cron: "0 3 * * *"
  push:
  
  workflow_dispatch:

jobs:
  update_versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout my IDE test branch
        uses: actions/checkout@v3
        with:
          # repository & branch have to be changed in the final code!
          repository: sarahffm/ide
          ref: test
          path: './ide'
        
      - name: Get versions
        run: |
          source ./ide/scripts/src/main/resources/scripts/functions
          doWarning "This is a test."
          DEVON_IDE_HOME=/home/runner/work/ide-mirrors/ide-mirrors/
          doDevonCommand test az
          
      #- name: Update available-versions file
        # not checking for changes yet
        #run: mv ./java/available_versions.tmp ./java/available_versions
        
      - name: Setup git user
        run: |
          git config --global user.email ${{secrets.BUILD_USER_EMAIL}}
          git config --global user.name ${{secrets.BUILD_USER}}
        
      - name: Commit and push changes
        run: |
          git add .
          git restore --staged .github/workflows/update-software-versions.yml
          git restore --staged ide
          echo 
          echo "Git status:
          git status
          git commit -m "Update available versions | GitHub Actions $GITHUB_WORKFLOW $GITHUB_RUN_NUMBER" || echo "No changes to commit."
          git push https://$secrets.BUILD_USER:$secrets.GHA_TOKEN@github.com/sarahffm/ide-mirrors.git
